name: deployment pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4
      - run: npn ci
      - run: npn test
      - run: npn run build
